# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moim' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moim
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'lottie-ios'
  pod 'GoogleSignIn'
  pod 'FirebaseAnalytics'
  target 'MoimTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoimUITests' do
    # Pods for testing
  end

end
